const ONE_MINUTE_IN_MS = 1000 * 60;

export const MAX_BILL_UPLOADS_PER_WINDOW = 5;
export const BILL_UPLOAD_RATE_LIMIT_WINDOW_IN_MS = ONE_MINUTE_IN_MS * 10;

export const MAX_BILL_SUMMARY_REQUESTS_PER_WINDOW = 200;
export const BILL_SUMMARY_RATE_LIMIT_WINDOW_IN_MS = ONE_MINUTE_IN_MS;